repos:
  - repo: local
    hooks:
      - id: golangci-format
        name: golangci-format
        entry: golangci-lint
        language: system
        args: [fmt]
        files: \.go$
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        args: [run, --fix]
        files: \.go$
        pass_filenames: false
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: go
        language: system
        args: [mod, tidy]
        files: \.(go|mod|sum)$
        pass_filenames: false
