services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easyflow-oauth2-server
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easyflow"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  valkey:
    image: valkey/valkey:alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:
  valkey-data: